import "../styles/globals.scss";
import type { AppProps } from "next/app";
import {
	CssBaseline,
	StyledEngineProvider,
	ThemeProvider,
} from "@mui/material";
import { theme } from "../theme";
import { Header } from "../components/header";
import "../styles/_mixin.scss";
import Head from "next/head";
function MyApp({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>TJourney</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ThemeProvider theme={theme}>
				<StyledEngineProvider injectFirst>
					<CssBaseline />
					<Header />
					<Component {...pageProps} />
				</StyledEngineProvider>
			</ThemeProvider>
		</>
	);
}

export default MyApp;
