import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "../components/header/header";
import { Button, MenuItem, Paper, Select, Typography } from "@mui/material";
import styles from "../styles/home.module.scss";
import React from "react";
import CommentIcon from "@mui/icons-material/Comment";
import { News } from "../components/news/news";
const Home: NextPage = () => {
	const [newsCategory, setNewsCategory] = React.useState(
		`${new Date().getDate()} июня`
	);
	return (
		<div className="page">
			<Head>
				<title>TJourney</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div className={styles.leftSide}></div>
			<div className={styles.content}>
				<Select
					variant="outlined"
					classes={{ outlined: styles.selectNewsCategory }}
					onChange={(e) => setNewsCategory(e.target.value)}
					value={newsCategory}
				>
					<MenuItem value="Все время">Все время</MenuItem>
					<MenuItem value="Месяц">Месяц</MenuItem>
					<MenuItem value={`${new Date().getDate()} июня`}>
						{`${new Date().getDate()} июня`}
					</MenuItem>
				</Select>
				<News />
				
			</div>
			<div className={styles.rightSide}></div>
		</div>
	);
};

export default Home;
